export const PRODUCT_COUNT_REQUEST = 'PRODUCT_COUNT_REQUEST'
export const PRODUCT_COUNT_SUCCESS = 'PRODUCT_COUNT_SUCCESS'
export const PRODUCT_COUNT_FAIL = 'PRODUCT_COUNT_FAIL'

export const USER_COUNT_REQUEST = 'USER_COUNT_REQUEST'
export const USER_COUNT_SUCCESS = 'USER_COUNT_SUCCESS'
export const USER_COUNT_FAIL = 'USER_COUNT_FAIL'

export const ORDER_COUNT_REQUEST = 'ORDER_COUNT_REQUEST'
export const ORDER_COUNT_SUCCESS = 'ORDER_COUNT_SUCCESS'
export const ORDER_COUNT_FAIL = 'ORDER_COUNT_FAIL'